export const SIGNUP_SUCCESS = 'signup/success'
export const SIGNIN_SUCCESS = 'signin/success'
export const SIGNUP_ERROR = 'signup/error'
export const SIGNIN_ERROR = 'signin/error'
export const SIGNIN_LOADING = 'signin/loading'
export const SIGNOUT_SUCCESS = 'logout/success'
